on:
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set all tracked file modification times to the time of their last commit
        run: |
          rev=HEAD
          for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do
              touch -d $(git log --pretty=format:%cI -1 "$rev" -- "$f") "$f";
          done
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: cabal-${{ hashFiles('chez-grater.cabal') }}
          restore-keys: |
            cabal-${{ hashFiles('chez-grater.cabal') }}
            cabal-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: false
      - run: cabal v2-update
      - run: cabal v2-test --test-log /dev/stdout --test-show-details always
