on:
  push: {}
  schedule:
    - cron: "0 5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            dist-newstyle
          key: cabal-${{ hashFiles('cheez.cabal') }}
          restore-keys: |
            cabal-${{ hashFiles('cheez.cabal') }}
            cabal-
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: false
      - run: cabal v2-test --test-log /dev/stdout --test-show-details always
